anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmBbdddvcssmfNgNfu8vgULnhTAcnrn841K5QVhh5VV'

[programs.devnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmBbdddvcssmfNgNfu8vgULnhTAcnrn841K5QVhh5VV'

[programs.testnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmBbdddvcssmfNgNfu8vgULnhTAcnrn841K5QVhh5VV'

[programs.localnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmBbdddvcssmfNgNfu8vgULnhTAcnrn841K5QVhh5VV'
